(function () {
$('.img1').css('display','none')
$('.img2').css('display','none')
$('.img3').css('display','none')
$('.img8').css('display','none')
$('.img7').css('display','none')
$('.img6').css('display','none')
$('.img5').css('display','none')
$('.mg2').hover(function(){
    $('.img4').css('display','none')
    $('.mg5').css('display','none')

$('.img2').css('display','none')
$('.img3').css('display','none')
$('.img8').css('display','none')
$('.img7').css('display','none')
$('.img6').css('display','none')

    $('.img1').css('display','block')
    $('.img5').css('display','block')
    
})
$('.mg2').hover(function(){
    $('.img4').css('display','none')
    $('.mg5').css('display','none')
    $('.img1').css('display','none')

$('.img3').css('display','none')
$('.img8').css('display','none')
$('.img7').css('display','none')

$('.img5').css('display','none')
    $('.img2').css('display','block')
    $('.img6').css('display','block')
    
})
$('.mg3').hover(function(){
    $('.img4').css('display','none')
    $('.mg5').css('display','none')
    $('.img1').css('display','none')
$('.img2').css('display','none')

$('.img8').css('display','none')
 
$('.img6').css('display','none')
$('.img5').css('display','none')
    $('.img3').css('display','block')
    $('.img7').css('display','block')
    
})
$('.li2').mouseenter(function(){
    $('.second').css('display','block');
})
$('.second').mouseenter(function(){
    $('.second').css('display','block');
})
$('.li2').mouseleave(function(){
    $('.second').css('display','none');
})
$('.second').mouseleave(function(){
    $('.second').css('display','none');
})
$('.li3').mouseenter(function(){
    $('.second1').css('display','block');
})
$('.second1').mouseenter(function(){
    $('.second1').css('display','block');
})
$('.li3').mouseleave(function(){
    $('.second1').css('display','none');
})
$('.second1').mouseleave(function(){
    $('.second1').css('display','none');
})
$('.li4').mouseenter(function(){
    $('.second2').css('display','block');
})
$('.second2').mouseenter(function(){
    $('.second2').css('display','block');
})
$('.li4').mouseleave(function(){
    $('.second2').css('display','none');
})
$('.second2').mouseleave(function(){
    $('.second2').css('display','none');
})
$('.li5').mouseenter(function(){
    $('.second3').css('display','block');
})
$('.second3').mouseenter(function(){
    $('.second3').css('display','block');
})
$('.li5').mouseleave(function(){
    $('.second3').css('display','none');
})
$('.second3').mouseleave(function(){
    $('.second3').css('display','none');
})
$('.weibo1').mouseenter(function(){
    $('.weobo').css('display','block');
})
$('.weibo1').mouseleave(function(){
    $('.weobo').css('display','none');
})
$('.weixin1').mouseenter(function(){
    $('.wexin').css('display','block');
})
$('.weixin1').mouseleave(function(){
    $('.wexin').css('display','none');
})
$('.shouji1').mouseenter(function(){
    $('.shouji').css('display','block');
})
$('.shouji1').mouseleave(function(){
    $('.shouji').css('display','none');
})
$('.shouji').mouseleave(function(){
    $('.shouji').css('display','none');
})
$('.shouji').mouseenter(function(){
    $('.shouji').css('display','block');
})
$('.wexin').mouseleave(function(){
    $('.wexin').css('display','none');
})
$('.wexin').mouseenter(function(){
    $('.wexin').css('display','block');
})
$('.weobo').mouseleave(function(){
    $('.weobo').css('display','none');
})
$('.weobo').mouseenter(function(){
    $('.weobo').css('display','block');
})
$('.shopping_cart').mouseleave(function(){
    $('.shopping_cart').css('display','none');
})
$('.shopping_cart').mouseenter(function(){
    $('.shopping_cart').css('display','block');
})
$('.shopping_cart1').mouseleave(function(){
    $('.shopping_cart').css('display','none');
})
$('.shopping_cart1').mouseenter(function(){
    $('.shopping_cart').css('display','block');
})
$('.nav_con').click(function(){
    location.href = 'http://localhost:1902/xiangmu/html/ListPage.html' ;
})
$('.second1 dl dt a' ).click(function(){
    location.href = 'http://localhost:1902/xiangmu/html/ListPage.html' ;
})
})()